### ISSUE TITLE
Conflicts between bocadillo and websockets

### ISSUE THREAD

**Issue by NeolithEra** [bocadilloproject/bocadillo#325]
Hi, users are unable to run **_bocadillo_** due to dependency conflict with _**websockets**_ package. 
As shown in the following full dependency graph of **_bocadillo_**, **_bocadillo_** requires _**websockets>=6.0**_ ，while **_uvicorn_** requires _**websockets==7.***_.

According to pip’s “first found wins” installation strategy, _**websockets==8.0.1**_ is the actually installed version.

However, _**websockets==8.0.1**_ does not satisfy _**websockets==7.***_.

### Dependency tree-----
```
bocadillo(version range:)
| +-aiodine(version range:<2.0,>=1.2.5)
| +-jinja2(version range:>=2.10.1)
| +-python-multipart(version range:)
| | +-six(version range:>=1.4.0)
| +-requests(version range:)
| +-starlette(version range:>=0.12.2,<0.13)
| +-typesystem(version range:>=0.2.2)
| +-uvicorn(version range:>=0.7,<0.9)
| | +-click(version range:==7.)
| | +-h11(version range:==0.8.)
| | +-websockets(version range:==7.)
| | +-httptools(version range:==0.0.13sys)
| | +-uvloop(version range:==0.12.sys)
| +-websockets(version range:>=6.0)
| +-whitenoise(version range:)
```

Thanks for your help.
Best,
Neolith

### Solution

Fix your direct dependency to be websockets>=6.0,<8. I have checked this revision will not affect your downstream projects now.

**Comment by NeolithEra** [comment]
Could you help me review this issue? I can submit a PR to solve this issue.

**Comment by florimondmanca** [comment]
Hi, thanks for reporting!

> According to pip’s “first found wins” installation strategy

Ooh, I actually wasn’t aware of this. :-)

> Fix your direct dependency to be websockets>=6.0,<8.

I’m thinking, since uvicorn actually *requires* a specific version of websockets, and I think we don’t actually have a constraint on its versions on our side, we can probably drop the dependency specification altogether and use whichever version uvicorn installs. This will prevent this issue from happening again once websockets turns 0.9.x and uvicorn wants to enforce it.

> Could you help me review this issue? I can submit a PR to solve this issue.

With great pleasure! Feel free to submit a PR and I’ll take a look at it. Thanks!
