### ISSUE TITLE
Optional query parameters?

### ISSUE THREAD

**Issue by darcyturk** [bocadilloproject/bocadillo#78]
Am yet to get optional query params to work using Bocadillo and here is what i'm working with from the Sports Reference Python API -> https://sportsreference.readthedocs.io/en/v0.3.1/

![messagesimage 1642559551](https://user-images.githubusercontent.com/16271621/50554897-0e7a0f80-0c78-11e9-83a7-19e01d1348db.png)

Here is my code:

```python
@nba.route('/schedule')
def get_schedule(req, res):
    param1 = req.query_params['team']
    schedule = Schedule(param1)
    res.media = [{
        'date': game.date,
        'game': game.game,
        'opponent_abbr': game.opponent_abbr,
        'result': game.result,
        'boxscore': game.boxscore_index
    } for game in schedule]
    pass
```

local address i use for above is http://localhost:8000/league/nba/schedule?team=LAC and works

![messagesimage 1708435009](https://user-images.githubusercontent.com/16271621/50555047-6ebe8080-0c7b-11e9-907d-a11725daa874.png)

...i would like to use the year param, but not with all my requests. When it's not provided it defaults to the this year's season and no matter what i try i get this error...

**_KeyError: 'year'_**

**Specs**
- OS: macOS 10.14.2
- Python Version: v3.7.1
- Bocadillo Version: v0.7.0

**Comment by florimondmanca** [comment]
Hi @darcyturk,

I went ahead and formatted your code with code fences for readability.

Your error is about the `year` key but I can't see it being pulled out from the query string in the code snippet you provided.

That said, the `query_params` attribute is a regular Python dictionary, so optional query parameters can be implemented using `.query_params.get("my_query_param", default_value)` instead of `query_params["my_query_param"]`. See here: https://stackoverflow.com/questions/11041405/why-dict-getkey-instead-of-dictkey

I'll add a hint on that in the docs. :)

**Comment by florimondmanca** [comment]
@darcyturk https://bocadilloproject.github.io/topics/http/requests.html#query-parameters

I'm closing this for now, if that doesn't fix it for you let me know.

**Comment by darcyturk** [comment]
@florimondmanca thank you it's fixed :)
